### ISSUE TITLE
Homebrew has updated ICU to 72.1

### ISSUE THREAD

**Issue by Boberro** [shivammathur/homebrew-php#1485]
Newly installed php versions from shivammathur/php no longer run, as homebrew updated to version 72.1

**PHP versions**
tested on 7.4, 8.1, 8.2

**To Reproduce**
Install any shivammathur/php version

**Screenshots/Logs**
    $php -v
    dyld[13817]: Library not loaded: /usr/local/opt/icu4c/lib/libicuio.71.dylib
    Referenced from: /usr/local/Cellar/php@8.1/8.1.14/bin/php
    Reason: tried: '/usr/local/opt/icu4c/lib/libicuio.71.dylib' (no such file), '/usr/local/lib/libicuio.71.dylib' (no such file), '/usr/lib/libicuio.71.dylib' (no such file), '/usr/local/Cellar/icu4c/72.1/lib/libicuio.71.dylib' (no such file), '/usr/local/lib/libicuio.71.dylib' (no such file), '/usr/lib/libicuio.71.dylib' (no such file)

**Comment by shivammathur** [comment]
@Boberro 
Should be fixed by https://github.com/shivammathur/homebrew-php/pull/1486. It will take 1-2 hours for the build to complete.

**Comment by shivammathur** [comment]
The runner crashed, so will take more time.

**Comment by AndresReyesDev** [comment]
I would like to take this opportunity to thank you @shivammathur for your help in this project.

**Comment by yurii-zhuravlov** [comment]
As a temporary solution in order to downgrade icu4c library to 71.1 version:
$ wget https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-src.tgz
$ tar xvfz icu4c-71_1-src.tgz
$ cd icu/sources
$ ./configure
$ make
And finally override symlink for icu4c (in my case locate in /opt/homebrew/opt/ directory)

**Comment by vintagesucks** [comment]
Alternative workaround by downgrading icu4c to 71.1 via brew ([via](https://stackoverflow.com/a/54273234)):

```sh
git -C $(brew --repo homebrew/core) fetch # you may need to add --unshallow here
cd $(brew --repo homebrew/core)
git checkout e3317b86c11c644e88c762e03eb7b310c3337587 -- Formula/icu4c.rb
brew uninstall  --ignore-dependencies icu4c
brew install icu4c
brew install shivammathur/php/php@8.2 # replace with desired version
git reset && git checkout . 
```

**Comment by shivammathur** [comment]
Fixed in #1486 

Please update your brew and PHP.

For example: For PHP 8.2
```zsh
brew update
brew upgrade shivammathur/php/php@8.2
```

If that doesn't work, please reinstall the PHP version along with `icu4c`.
```zsh
brew update
brew reinstall icu4c shivammathur/php/php@8.2
```

Restart your terminal and verify the PHP version and ICU version
```zsh
php -v
php -i | grep "ICU version"
```

At last, [restart your webserver](https://github.com/shivammathur/homebrew-php#restart-your-webserver).

**Comment by shengslogar** [comment]
@shivammathur Boss! Thank you!

**Comment by AndresReyesDev** [comment]
Muchas gracias! 🎉

**Comment by Bosphoramus** [comment]
Thank you!
