### ISSUE TITLE
How to use php with openssl 1.1

### ISSUE THREAD

**Issue by limingxinleo** [shivammathur/homebrew-php#1900]
PHP with openssl@3 has some bugs.

```php
var_dump(openssl_encrypt('12345', 'bf', 'xxxxxxxx', 0, 'xxxxxxxx'));
```

When I run it in php8 with openssl@1.1, it works.

But I run it with openssl@3.0, it will be broken.

**Comment by shivammathur** [comment]
@limingxinleo 
Instead of trying to downgrade openssl, enable legacy providers in it.

1. open "$(brew --prefix)"/etc/openssl@3/openssl.cnf
2. Find `[default_sect]` section in the file and uncomment `activate = 1` under it. Then add the `legact_sect` section under that.

```cnf
[default_sect]
activate = 1
[legacy_sect]
activate = 1
```

Then find the [provider_sect] and change it to the following:
```cnf
[provider_sect]
default = default_sect
legacy = legacy_sect
```

Save the file and run the following command, it should show both default and legacy providers
```zsh
openssl list -providers
```

Your code should work then.

**Comment by aryojamousi** [comment]
@shivammathur can't thank you enough for this solution! :)
